Fixed correct report URI when using ReportPerSite option
seanhamlin/site-audit pull request #212
Opened 2018-10-11 16:13 UTC by thomaslafon

Wrong current URI was shown in reports when using option --report-per-site.

Actually this part of code above, is always pushing the last $uri of $uris array in $target->uri, resulting in the same domain showing up on every report.

This fix sets the value to ```$assessment->uri``` if "reportPerSite" option is used.

```
foreach ($uris as $uri) {
      try {
        $target->setUri($uri);
      }
      catch (\Drutiny\Target\InvalidTargetException $e) {
        Container::getLogger()->warning("Target cannot be evaluated: " . $e->getMessage());
        $progress->advance(count($policyDefinitions));
        continue;
      }

      $assessment = new Assessment($uri);
      $assessment->assessTarget($target, $policies, $start, $end, $input->getOption('remediate'));
      $results[$uri] = $assessment;
    }
```

2018-10-11 19:26 UTC, fiasco requested changes

2018-10-11 19:26 UTC, fiasco commented on src/Report/Format/JSON.php
> +    $schema['summary'] = $profile->reportPerSite() === true ? $assessment->uri() : $target->uri();
Since Assessment was introduced, I think its the authoritative source for URI over a Target, so I think it should be the defacto rather than only for reportPerSite.

Shall we remove the condition and just go with `$assessment->uri();`?

2018-10-16 13:02 UTC, thomaslafon commented on src/Report/Format/JSON.php
> +    $schema['summary'] = $profile->reportPerSite() === true ? $assessment->uri() : $target->uri();
Agreed. PR changed.

2018-10-16 20:54 UTC, fiasco approved these changes

2018-10-16 20:54 UTC, merged

2018-10-16 20:54 UTC, fiasco commented
Thanks @thomaslafon !