Issue 45: Throw exception if profile doesn't exist
seanhamlin/site-audit pull request #53
Opened 2017-01-26 23:25 UTC by steveworley

- Updates Profile class so that it only pertains to a "Profile"
- Adds a ProfileController class to abstract loading/saving
- Updates Audit commands so that they now load via the controller
- Updates HtaccessRedirects to prevent errors when generating a profile

Fixes #45

2017-01-26 23:26 UTC, steveworley commented
@seanhamlin I created #52 off of this - I had to update the `ProfileCreateCommand` to go with a more MVC approach for the Profile class and when I was testing I found issues with the `array_flip` that the Profile class does when it is adding a check.

2017-01-27 00:05 UTC, seanhamlin requested changes

2017-01-27 00:05 UTC, seanhamlin commented on src/Profile/Profile.php
> +    file_put_contents(json_encode($registry), '/Users/steven.worley/repos/site-audit/file.txt');
looks like it is debug.

2017-01-27 00:05 UTC, seanhamlin commented on src/Profile/ProfileController.php
> +    throw new ProfileNotFoundException($machine_name, 0);
w00t

2017-01-27 09:10 UTC, merged

2017-01-27 09:11 UTC, seanhamlin commented
Nice work @steveworley !