Security checks for D7 from Drush Audit
seanhamlin/site-audit pull request #71
Opened 2017-03-02 05:52 UTC by steveworley

2017-03-06 22:50 UTC, seanhamlin commented
In discussion with @steveworley, this PR still needs more work before it can be merged. Ideally it would also:

* have merged master
* have tests all passing

2017-03-28 03:09 UTC, steveworley commented
Woo! @seanhamlin fixed up the test and merged master :) I added some more tests as well for the new checks that I've added.

2017-03-28 03:10 UTC, steveworley commented
This branch aims to make my Drush Audit tool obsolete so I'll discontinue that project and continue contributing to this one.

2017-03-28 07:36 UTC, seanhamlin requested changes
Wow, looking nice @steveworley! A few things need tidying.

2017-03-28 07:36 UTC, seanhamlin commented on composer.json
> +        "ircmaxell/random-lib": "^1.2",
I have deprecated this lib, in favour of the PHP7 backwards lib random_compat. Is there some reason why you need this?

2017-03-28 07:36 UTC, seanhamlin commented on src/Base/PhantomasCaller.php
> +      $username = getenv('SITE_AUDIT_HTTP_AUTH_USER');
s/SITE_AUDIT/DRUTINY/g

2017-03-28 07:36 UTC, seanhamlin commented on src/Check/D7/ViewsPagination.php
> +use Drutiny\Helpers\Serializer;
I do like this 'Helpers' namespace. I can move a few classes into there.

2017-03-28 07:36 UTC, seanhamlin commented on src/Check/Security/D7/TextFormat.php
> +    $sql = "SELECT format, name, cache, status, weight FROM filter_format ff;";
Use more `{}` around table names.

2017-03-28 07:36 UTC, seanhamlin commented on src/Check/Security/D7/ViewsAccess.php
> +    $sql = "SELECT vv.vid, vv.name, vv.description, vv.human_name, vd.id, vd.display_title, vd.display_options, vd.display_plugin
If it helps, I have written a `runScript` method in the drush controller, to which you can execute raw PHP in the context of the site. This maybe of use here.

2017-03-28 07:36 UTC, seanhamlin commented on src/Check/Security/D7/ViewsAccess.php
> +    $sql = "SELECT vv.vid, vv.name, vv.description, vv.human_name, vd.id, vd.display_title, vd.display_options, vd.display_plugin
See the 'MissingModules' check

2017-03-28 08:42 UTC, seanhamlin commented
Also, w00t for combining powers!

2017-03-30 04:04 UTC, steveworley commented on composer.json
> +        "ircmaxell/random-lib": "^1.2",
Think that might have been a bad merge resolution.

2017-04-11 02:31 UTC, seanhamlin requested changes

2017-04-11 02:31 UTC, seanhamlin commented on src/Base/PhantomasCaller.php
> +    // export DRUTINY_HTTP_AUTH_USER=[PASSWORD]
bad merge.

2017-04-11 02:31 UTC, seanhamlin commented on src/scripts/ViewsGetAllViews.php
> +/**
If this comment is made with `//` then it will be stripped prior to base64 encoding. The regex to strip multiline comments is a lot harder to do.

2017-04-11 02:31 UTC, seanhamlin commented on tests/src/Unit/Security/ViewsAccessBaseTest.php
> +
empty test?

2017-04-17 22:44 UTC, seanhamlin requested changes

2017-04-17 22:44 UTC, seanhamlin commented on composer.json
> +        "guzzlehttp/guzzle": "^6.2",
the lock file needs to be committed too.

2017-04-17 22:44 UTC, seanhamlin commented on src/Base/PhantomasCaller.php
> +    // export DRUTINY_HTTP_AUTH_USER=[PASSWORD]
`DRUTINY_HTTP_AUTH_PASS`

2017-10-16 03:33 UTC, closed without merging